### ISSUE TITLE
Loading a module with a table directive gives error.

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/tabling_library#1]
Reproducible by (1) putting a simple tabling problem into a module file:

``` prolog
:- module(tab, [tab/2]).
:- use_module('/home/wbeek/Git/tabling_library/tabling').
:- table tab/2.

tab(X, Z) :- tab(X, Y), tab(Y, Z).
tab(X, Y) :- tab0(X, Y).
tab0(1, 2). tab0(2, 3).
```

... then (2) load the module:

``` prolog
?- [library(tab)].
ERROR: /home/wbeek/lib/swipl/pack/Prolog-Library-Collection/prolog/tab.pl:5:
    Wrong context: table/1 can only be used in a directive
Warning: /home/wbeek/lib/swipl/pack/Prolog-Library-Collection/prolog/tab.pl:5:
    Goal (directive) failed: tab:table(tab/2)
```

**Comment by JanWielemaker** [comment]
I can't reproduce this.  Same file, updated path to tabling.pl.  Loads just fine.  Could it be you've
got something loaded that upsets term expansion?

**Comment by wouterbeek** [comment]
This can be reproduced as follows:
1. `git clone https://github.com/wouterbeek/plRdfTabling`
2. `cd plRdfTabling`
3. `swipl install.pl`
4. `swipl rdf_tab.pl`

This assumes that the tabling module is available on Prolog's library path, i.e., `library(tabling_library/tabling)`.

**Comment by JanWielemaker** [comment]
Can I install this also without installing all sorts of packs?  I don't 
really
like messing around with my pack installations to test something ...

Looking at the code, as the README of tabling says, you cannot run 
tabling in
debug mode at the moment.

```
--- Jan
```
